// <auto-generated />
using System;
using AutoTest.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoTest.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412061332_AddRoadSignsAndMarkings")]
    partial class AddRoadSignsAndMarkings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("autotest")
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoTest.Domain.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "StartsAt", "ExpiresAt");

                    b.ToTable("Announcements", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.AnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.ColorVisionPlate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlternateAnswer")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpectedAnswer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PlateNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("ColorVisionPlates", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.ExamPoolRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExamTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ExamTemplateId");

                    b.ToTable("ExamPoolRules", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.ExamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CorrectAnswers")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ExamTemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LicenseCategory")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TicketNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeLimitPerQuestionSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeTakenSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt")
                        .HasFilter("\"Status\" = 1");

                    b.HasIndex("ExamTemplateId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("UserId", "Mode");

                    b.HasIndex("UserId", "Status");

                    b.HasIndex("UserId", "Status", "Mode", "CompletedAt");

                    b.ToTable("ExamSessions", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.ExamTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PassingScore")
                        .HasColumnType("integer");

                    b.Property<int>("TimeLimitMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeLimitPerQuestionSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ExamTemplates", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.FirstAidProcedure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("FirstAidProcedures", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.FirstAidStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FirstAidProcedureId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirstAidProcedureId", "StepOrder");

                    b.ToTable("FirstAidSteps", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.GlossaryCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("GlossaryCategories", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.GlossaryTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GlossaryCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid[]>("RelatedQuestionIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GlossaryCategoryId");

                    b.ToTable("GlossaryTerms", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.HazardLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HazardClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("HazardLabels", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.LeaderboardSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("XpValue")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Period");

                    b.HasIndex("Period", "SnapshotDate", "Rank");

                    b.ToTable("LeaderboardSnapshots", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.OtpRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber", "IsVerified");

                    b.ToTable("OtpRequests", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountInTiyins")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("UZS");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("CreatedAt", "Status");

                    b.HasIndex("Status", "Provider");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("PaymentTransactions", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AvgTimeSec")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("LicenseCategory")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TicketNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TicketNumber");

                    b.HasIndex("CategoryId", "Difficulty")
                        .HasFilter("\"Status\" = 1");

                    b.HasIndex("TicketNumber", "Status");

                    b.ToTable("Questions", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.RoadMarking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MarkingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MarkingType")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("MarkingCode")
                        .IsUnique();

                    b.HasIndex("MarkingType");

                    b.HasIndex("MarkingType", "SortOrder");

                    b.ToTable("RoadMarkings", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.RoadSign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SignCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsActive");

                    b.HasIndex("SignCode")
                        .IsUnique();

                    b.HasIndex("CategoryId", "SortOrder");

                    b.ToTable("RoadSigns", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.RoadSignCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("RoadSignCategories", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.SessionQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SelectedAnswerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TimeSpentSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SelectedAnswerId");

                    b.HasIndex("ExamSessionId", "Order");

                    b.HasIndex("QuestionId", "ExamSessionId")
                        .HasFilter("\"IsCorrect\" = false");

                    b.ToTable("SessionQuestions", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean");

                    b.Property<string>("CardToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PaymentProvider")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId", "Status", "ExpiresAt");

                    b.ToTable("Subscriptions", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("PriceInTiyins")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.TrafficFine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("PenaltyAmountTiyins")
                        .HasColumnType("bigint");

                    b.Property<long?>("PenaltyMaxTiyins")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArticleNumber");

                    b.HasIndex("IsActive");

                    b.ToTable("TrafficFines", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthProvider")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LastStudyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PreferredLanguage")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalXp")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("\"PhoneNumber\" IS NOT NULL");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasFilter("\"TelegramId\" IS NOT NULL");

                    b.ToTable("Users", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.UserCategoryStat", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("UserCategoryStats", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.UserDailyStats", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StatDate")
                        .HasColumnType("date");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer");

                    b.Property<int>("ExamsCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionsAnswered")
                        .HasColumnType("integer");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("integer");

                    b.Property<long>("XpEarned")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "StatDate");

                    b.HasIndex("UserId", "StatDate")
                        .IsDescending(false, true);

                    b.ToTable("UserDailyStats", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FcmToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeviceId")
                        .IsUnique();

                    b.ToTable("UserDevices", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.UserFavoriteQuestion", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavoriteQuestions", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.UserQuestionState", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeitnerBox")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("NextReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId", "LastAttemptAt");

                    b.HasIndex("UserId", "NextReviewDate");

                    b.ToTable("UserQuestionStates", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.UserSetting", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("UserId", "Key");

                    b.ToTable("UserSettings", "autotest");
                });

            modelBuilder.Entity("QuestionTags", b =>
                {
                    b.Property<Guid>("QuestionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("QuestionTags", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Announcement", b =>
                {
                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Content", b1 =>
                        {
                            b1.Property<Guid>("AnnouncementId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AnnouncementId");

                            b1.ToTable("Announcements", "autotest");

                            b1.ToJson("Content");

                            b1.WithOwner()
                                .HasForeignKey("AnnouncementId");
                        });

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<Guid>("AnnouncementId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AnnouncementId");

                            b1.ToTable("Announcements", "autotest");

                            b1.ToJson("Title");

                            b1.WithOwner()
                                .HasForeignKey("AnnouncementId");
                        });

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.AnswerOption", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Text", b1 =>
                        {
                            b1.Property<Guid>("AnswerOptionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AnswerOptionId");

                            b1.ToTable("AnswerOptions", "autotest");

                            b1.ToJson("Text");

                            b1.WithOwner()
                                .HasForeignKey("AnswerOptionId");
                        });

                    b.Navigation("Question");

                    b.Navigation("Text")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Category", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CategoryId");

                            b1.ToTable("Categories", "autotest");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CategoryId");

                            b1.ToTable("Categories", "autotest");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.ExamPoolRule", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoTest.Domain.Entities.ExamTemplate", "ExamTemplate")
                        .WithMany("PoolRules")
                        .HasForeignKey("ExamTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ExamTemplate");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.ExamSession", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.ExamTemplate", "ExamTemplate")
                        .WithMany()
                        .HasForeignKey("ExamTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoTest.Domain.Entities.User", "User")
                        .WithMany("ExamSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamTemplate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.ExamTemplate", b =>
                {
                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<Guid>("ExamTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ExamTemplateId");

                            b1.ToTable("ExamTemplates", "autotest");

                            b1.ToJson("Title");

                            b1.WithOwner()
                                .HasForeignKey("ExamTemplateId");
                        });

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.FirstAidProcedure", b =>
                {
                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("FirstAidProcedureId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("FirstAidProcedureId");

                            b1.ToTable("FirstAidProcedures", "autotest");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("FirstAidProcedureId");
                        });

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Summary", b1 =>
                        {
                            b1.Property<Guid>("FirstAidProcedureId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("FirstAidProcedureId");

                            b1.ToTable("FirstAidProcedures", "autotest");

                            b1.ToJson("Summary");

                            b1.WithOwner()
                                .HasForeignKey("FirstAidProcedureId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.FirstAidStep", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.FirstAidProcedure", "Procedure")
                        .WithMany("Steps")
                        .HasForeignKey("FirstAidProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("FirstAidStepId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("FirstAidStepId");

                            b1.ToTable("FirstAidSteps", "autotest");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("FirstAidStepId");
                        });

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<Guid>("FirstAidStepId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("FirstAidStepId");

                            b1.ToTable("FirstAidSteps", "autotest");

                            b1.ToJson("Title");

                            b1.WithOwner()
                                .HasForeignKey("FirstAidStepId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Procedure");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.GlossaryCategory", b =>
                {
                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("GlossaryCategoryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("GlossaryCategoryId");

                            b1.ToTable("GlossaryCategories", "autotest");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("GlossaryCategoryId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.GlossaryTerm", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.GlossaryCategory", "Category")
                        .WithMany("Terms")
                        .HasForeignKey("GlossaryCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Definition", b1 =>
                        {
                            b1.Property<Guid>("GlossaryTermId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("GlossaryTermId");

                            b1.ToTable("GlossaryTerms", "autotest");

                            b1.ToJson("Definition");

                            b1.WithOwner()
                                .HasForeignKey("GlossaryTermId");
                        });

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Term", b1 =>
                        {
                            b1.Property<Guid>("GlossaryTermId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("GlossaryTermId");

                            b1.ToTable("GlossaryTerms", "autotest");

                            b1.ToJson("Term");

                            b1.WithOwner()
                                .HasForeignKey("GlossaryTermId");
                        });

                    b.Navigation("Category");

                    b.Navigation("Definition")
                        .IsRequired();

                    b.Navigation("Term")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.HazardLabel", b =>
                {
                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("HazardLabelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("HazardLabelId");

                            b1.ToTable("HazardLabels", "autotest");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("HazardLabelId");
                        });

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("HazardLabelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("HazardLabelId");

                            b1.ToTable("HazardLabels", "autotest");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("HazardLabelId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.LeaderboardSnapshot", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoTest.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Question", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Explanation", b1 =>
                        {
                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("QuestionId");

                            b1.ToTable("Questions", "autotest");

                            b1.ToJson("Explanation");

                            b1.WithOwner()
                                .HasForeignKey("QuestionId");
                        });

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Text", b1 =>
                        {
                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("QuestionId");

                            b1.ToTable("Questions", "autotest");

                            b1.ToJson("Text");

                            b1.WithOwner()
                                .HasForeignKey("QuestionId");
                        });

                    b.Navigation("Category");

                    b.Navigation("Explanation")
                        .IsRequired();

                    b.Navigation("Text")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.RoadMarking", b =>
                {
                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("RoadMarkingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RoadMarkingId");

                            b1.ToTable("RoadMarkings", "autotest");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("RoadMarkingId");
                        });

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("RoadMarkingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RoadMarkingId");

                            b1.ToTable("RoadMarkings", "autotest");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("RoadMarkingId");
                        });

                    b.Navigation("Description");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.RoadSign", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.RoadSignCategory", "Category")
                        .WithMany("Signs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("RoadSignId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RoadSignId");

                            b1.ToTable("RoadSigns", "autotest");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("RoadSignId");
                        });

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("RoadSignId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RoadSignId");

                            b1.ToTable("RoadSigns", "autotest");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("RoadSignId");
                        });

                    b.Navigation("Category");

                    b.Navigation("Description");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.RoadSignCategory", b =>
                {
                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("RoadSignCategoryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RoadSignCategoryId");

                            b1.ToTable("RoadSignCategories", "autotest");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("RoadSignCategoryId");
                        });

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("RoadSignCategoryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RoadSignCategoryId");

                            b1.ToTable("RoadSignCategories", "autotest");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("RoadSignCategoryId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.SessionQuestion", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.ExamSession", "ExamSession")
                        .WithMany("SessionQuestions")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoTest.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoTest.Domain.Entities.AnswerOption", "SelectedAnswer")
                        .WithMany()
                        .HasForeignKey("SelectedAnswerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExamSession");

                    b.Navigation("Question");

                    b.Navigation("SelectedAnswer");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoTest.Domain.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionPlanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SubscriptionPlanId");

                            b1.ToTable("SubscriptionPlans", "autotest");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionPlanId");
                        });

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionPlanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SubscriptionPlanId");

                            b1.ToTable("SubscriptionPlans", "autotest");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionPlanId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Tag", b =>
                {
                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("TagId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TagId");

                            b1.ToTable("Tags", "autotest");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("TagId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.TrafficFine", b =>
                {
                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "AdditionalNotes", b1 =>
                        {
                            b1.Property<Guid>("TrafficFineId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TrafficFineId");

                            b1.ToTable("TrafficFines", "autotest");

                            b1.ToJson("AdditionalNotes");

                            b1.WithOwner()
                                .HasForeignKey("TrafficFineId");
                        });

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "ViolationDescription", b1 =>
                        {
                            b1.Property<Guid>("TrafficFineId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TrafficFineId");

                            b1.ToTable("TrafficFines", "autotest");

                            b1.ToJson("ViolationDescription");

                            b1.WithOwner()
                                .HasForeignKey("TrafficFineId");
                        });

                    b.Navigation("AdditionalNotes");

                    b.Navigation("ViolationDescription")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.UserCategoryStat", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoTest.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.UserDailyStats", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.User", "User")
                        .WithMany("DailyStats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.UserDevice", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.UserFavoriteQuestion", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.Question", "Question")
                        .WithMany("FavoritedBy")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoTest.Domain.Entities.User", "User")
                        .WithMany("FavoriteQuestions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.UserQuestionState", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoTest.Domain.Entities.User", "User")
                        .WithMany("UserQuestionStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.UserSetting", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.User", "User")
                        .WithMany("Settings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuestionTags", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoTest.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.ExamSession", b =>
                {
                    b.Navigation("SessionQuestions");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.ExamTemplate", b =>
                {
                    b.Navigation("PoolRules");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.FirstAidProcedure", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.GlossaryCategory", b =>
                {
                    b.Navigation("Terms");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Question", b =>
                {
                    b.Navigation("AnswerOptions");

                    b.Navigation("FavoritedBy");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.RoadSignCategory", b =>
                {
                    b.Navigation("Signs");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.User", b =>
                {
                    b.Navigation("DailyStats");

                    b.Navigation("Devices");

                    b.Navigation("ExamSessions");

                    b.Navigation("FavoriteQuestions");

                    b.Navigation("Settings");

                    b.Navigation("Subscriptions");

                    b.Navigation("UserQuestionStates");
                });
#pragma warning restore 612, 618
        }
    }
}
