// <auto-generated />
using System;
using AutoTest.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoTest.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("autotest")
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoTest.Domain.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_announcements");

                    b.HasIndex("IsActive", "StartsAt", "ExpiresAt")
                        .HasDatabaseName("ix_announcements_is_active_starts_at_expires_at");

                    b.ToTable("announcements", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.AnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_answer_options");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_answer_options_question_id");

                    b.ToTable("answer_options", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("text")
                        .HasColumnName("old_values");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_parent_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_slug");

                    b.ToTable("categories", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.ExamPoolRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<Guid>("ExamTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_template_id");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer")
                        .HasColumnName("question_count");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_exam_pool_rules");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_exam_pool_rules_category_id");

                    b.HasIndex("ExamTemplateId")
                        .HasDatabaseName("ix_exam_pool_rules_exam_template_id");

                    b.ToTable("exam_pool_rules", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.ExamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int?>("CorrectAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answers");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ExamTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_template_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("LicenseCategory")
                        .HasColumnType("integer")
                        .HasColumnName("license_category");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("TicketNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_number");

                    b.Property<int?>("TimeTakenSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("time_taken_seconds");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_exam_sessions");

                    b.HasIndex("ExamTemplateId")
                        .HasDatabaseName("ix_exam_sessions_exam_template_id");

                    b.HasIndex("UserId", "Mode")
                        .HasDatabaseName("ix_exam_sessions_user_id_mode");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_exam_sessions_user_id_status");

                    b.ToTable("exam_sessions", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.ExamTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("PassingScore")
                        .HasColumnType("integer")
                        .HasColumnName("passing_score");

                    b.Property<int>("TimeLimitMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_minutes");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("total_questions");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_exam_templates");

                    b.ToTable("exam_templates", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.OtpRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_otp_requests");

                    b.HasIndex("PhoneNumber", "IsVerified")
                        .HasDatabaseName("ix_otp_requests_phone_number_is_verified");

                    b.ToTable("otp_requests", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountInTiyins")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_in_tiyins");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("UZS")
                        .HasColumnName("currency");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_transaction_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_payment_transactions");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_payment_transactions_subscription_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_payment_transactions_user_id_status");

                    b.ToTable("payment_transactions", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("LicenseCategory")
                        .HasColumnType("integer")
                        .HasColumnName("license_category");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thumbnail_url");

                    b.Property<int>("TicketNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_number");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("TicketNumber")
                        .HasDatabaseName("ix_questions_ticket_number");

                    b.HasIndex("CategoryId", "Difficulty")
                        .HasDatabaseName("ix_questions_category_id_difficulty")
                        .HasFilter("is_active = true");

                    b.ToTable("questions", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.SessionQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExamSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_session_id");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<Guid?>("SelectedAnswerId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_answer_id");

                    b.Property<int?>("TimeSpentSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("time_spent_seconds");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_session_questions");

                    b.HasIndex("ExamSessionId")
                        .HasDatabaseName("ix_session_questions_exam_session_id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_session_questions_question_id");

                    b.HasIndex("SelectedAnswerId")
                        .HasDatabaseName("ix_session_questions_selected_answer_id");

                    b.ToTable("session_questions", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_renew");

                    b.Property<string>("CardToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("card_token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int?>("PaymentProvider")
                        .HasColumnType("integer")
                        .HasColumnName("payment_provider");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_subscriptions_plan_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_subscriptions_user_id");

                    b.ToTable("subscriptions", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("features");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("PriceInTiyins")
                        .HasColumnType("bigint")
                        .HasColumnName("price_in_tiyins");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subscription_plans");

                    b.ToTable("subscription_plans", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_system_settings");

                    b.ToTable("system_settings", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_slug");

                    b.ToTable("tags", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AuthProvider")
                        .HasColumnType("integer")
                        .HasColumnName("auth_provider");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocked");

                    b.Property<DateTimeOffset?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<int>("PreferredLanguage")
                        .HasColumnType("integer")
                        .HasColumnName("preferred_language");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone_number")
                        .HasFilter("phone_number IS NOT NULL");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_telegram_id")
                        .HasFilter("telegram_id IS NOT NULL");

                    b.ToTable("users", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.UserCategoryStat", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<int>("CorrectAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("correct_attempts");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("total_attempts");

                    b.HasKey("UserId", "CategoryId")
                        .HasName("pk_user_category_stats");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_user_category_stats_category_id");

                    b.ToTable("user_category_stats", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device_name");

                    b.Property<string>("FcmToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fcm_token");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<int>("Platform")
                        .HasColumnType("integer")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_devices");

                    b.HasIndex("UserId", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_devices_user_id_device_id");

                    b.ToTable("user_devices", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.UserQuestionState", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("CorrectAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("correct_attempts");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<int>("LeitnerBox")
                        .HasColumnType("integer")
                        .HasColumnName("leitner_box");

                    b.Property<DateTimeOffset>("NextReviewDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_review_date");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("total_attempts");

                    b.HasKey("UserId", "QuestionId")
                        .HasName("pk_user_question_states");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_user_question_states_question_id");

                    b.ToTable("user_question_states", "autotest");
                });

            modelBuilder.Entity("question_tags", b =>
                {
                    b.Property<Guid>("QuestionsId")
                        .HasColumnType("uuid")
                        .HasColumnName("questions_id");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid")
                        .HasColumnName("tags_id");

                    b.HasKey("QuestionsId", "TagsId")
                        .HasName("pk_question_tags");

                    b.HasIndex("TagsId")
                        .HasDatabaseName("ix_question_tags_tags_id");

                    b.ToTable("question_tags", "autotest");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Announcement", b =>
                {
                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Content", b1 =>
                        {
                            b1.Property<Guid>("AnnouncementId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AnnouncementId");

                            b1.ToTable("announcements", "autotest");

                            b1.ToJson("content");

                            b1.WithOwner()
                                .HasForeignKey("AnnouncementId")
                                .HasConstraintName("fk_announcements_announcements_id");
                        });

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<Guid>("AnnouncementId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AnnouncementId");

                            b1.ToTable("announcements", "autotest");

                            b1.ToJson("title");

                            b1.WithOwner()
                                .HasForeignKey("AnnouncementId")
                                .HasConstraintName("fk_announcements_announcements_id");
                        });

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.AnswerOption", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answer_options_questions_question_id");

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Text", b1 =>
                        {
                            b1.Property<Guid>("AnswerOptionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AnswerOptionId");

                            b1.ToTable("answer_options", "autotest");

                            b1.ToJson("text");

                            b1.WithOwner()
                                .HasForeignKey("AnswerOptionId")
                                .HasConstraintName("fk_answer_options_answer_options_id");
                        });

                    b.Navigation("Question");

                    b.Navigation("Text")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Category", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_id");

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CategoryId");

                            b1.ToTable("categories", "autotest");

                            b1.ToJson("description");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId")
                                .HasConstraintName("fk_categories_categories_id");
                        });

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CategoryId")
                                .HasName("pk_categories");

                            b1.ToTable("categories", "autotest");

                            b1.ToJson("name");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId")
                                .HasConstraintName("fk_categories_categories_category_id");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.ExamPoolRule", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_pool_rules_categories_category_id");

                    b.HasOne("AutoTest.Domain.Entities.ExamTemplate", "ExamTemplate")
                        .WithMany("PoolRules")
                        .HasForeignKey("ExamTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_pool_rules_exam_templates_exam_template_id");

                    b.Navigation("Category");

                    b.Navigation("ExamTemplate");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.ExamSession", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.ExamTemplate", "ExamTemplate")
                        .WithMany()
                        .HasForeignKey("ExamTemplateId")
                        .HasConstraintName("fk_exam_sessions_exam_templates_exam_template_id");

                    b.HasOne("AutoTest.Domain.Entities.User", "User")
                        .WithMany("ExamSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_sessions_users_user_id");

                    b.Navigation("ExamTemplate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.ExamTemplate", b =>
                {
                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<Guid>("ExamTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ExamTemplateId");

                            b1.ToTable("exam_templates", "autotest");

                            b1.ToJson("title");

                            b1.WithOwner()
                                .HasForeignKey("ExamTemplateId")
                                .HasConstraintName("fk_exam_templates_exam_templates_id");
                        });

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .HasConstraintName("fk_payment_transactions_subscriptions_subscription_id");

                    b.HasOne("AutoTest.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_transactions_users_user_id");

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Question", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_categories_category_id");

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Explanation", b1 =>
                        {
                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("QuestionId");

                            b1.ToTable("questions", "autotest");

                            b1.ToJson("explanation");

                            b1.WithOwner()
                                .HasForeignKey("QuestionId")
                                .HasConstraintName("fk_questions_questions_id");
                        });

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Text", b1 =>
                        {
                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("QuestionId");

                            b1.ToTable("questions", "autotest");

                            b1.ToJson("text");

                            b1.WithOwner()
                                .HasForeignKey("QuestionId")
                                .HasConstraintName("fk_questions_questions_id");
                        });

                    b.Navigation("Category");

                    b.Navigation("Explanation")
                        .IsRequired();

                    b.Navigation("Text")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.SessionQuestion", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.ExamSession", "ExamSession")
                        .WithMany("SessionQuestions")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_questions_exam_sessions_exam_session_id");

                    b.HasOne("AutoTest.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_questions_questions_question_id");

                    b.HasOne("AutoTest.Domain.Entities.AnswerOption", "SelectedAnswer")
                        .WithMany()
                        .HasForeignKey("SelectedAnswerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_session_questions_answer_options_selected_answer_id");

                    b.Navigation("ExamSession");

                    b.Navigation("Question");

                    b.Navigation("SelectedAnswer");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_subscription_plans_plan_id");

                    b.HasOne("AutoTest.Domain.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_users_user_id");

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionPlanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SubscriptionPlanId");

                            b1.ToTable("subscription_plans", "autotest");

                            b1.ToJson("description");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionPlanId")
                                .HasConstraintName("fk_subscription_plans_subscription_plans_id");
                        });

                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionPlanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SubscriptionPlanId");

                            b1.ToTable("subscription_plans", "autotest");

                            b1.ToJson("name");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionPlanId")
                                .HasConstraintName("fk_subscription_plans_subscription_plans_id");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Tag", b =>
                {
                    b.OwnsOne("AutoTest.Domain.Common.ValueObjects.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("TagId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UzLatin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TagId");

                            b1.ToTable("tags", "autotest");

                            b1.ToJson("name");

                            b1.WithOwner()
                                .HasForeignKey("TagId")
                                .HasConstraintName("fk_tags_tags_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.UserCategoryStat", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_category_stats_categories_category_id");

                    b.HasOne("AutoTest.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_category_stats_users_user_id");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.UserDevice", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_devices_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.UserQuestionState", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_question_states_questions_question_id");

                    b.HasOne("AutoTest.Domain.Entities.User", "User")
                        .WithMany("UserQuestionStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_question_states_users_user_id");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("question_tags", b =>
                {
                    b.HasOne("AutoTest.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_tags_questions_questions_id");

                    b.HasOne("AutoTest.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_tags_tags_tags_id");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.ExamSession", b =>
                {
                    b.Navigation("SessionQuestions");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.ExamTemplate", b =>
                {
                    b.Navigation("PoolRules");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("AutoTest.Domain.Entities.User", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("ExamSessions");

                    b.Navigation("Subscriptions");

                    b.Navigation("UserQuestionStates");
                });
#pragma warning restore 612, 618
        }
    }
}
